import {FISH,RARITIES} from './config.mjs';
import {types,artwork} from '../starter/starter-ui.js?v=starter-gifs-5';
export const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const number=n=>n.toLocaleString('it-IT',{maximumFractionDigits:2});
export const button=(id,label,disabled=false,extra='')=>`<button type="button" data-action="${id}" ${disabled?'disabled':''} ${extra}>${label}</button>`;
export function fishArt(id){const p=FISH[id],url=new URL(p.asset||`../../${id}.png`,import.meta.url);return `<img class="pokemon" src="${url}" alt="${p.name}" width="150" height="150">`;}
export const badge=r=>`<span class="rarity ${r}">${RARITIES[r].label}</span>`;
export function FishingScene(phase,castLabel="Lancia la lenza"){const biting=phase==='timing';return `<div class="fishing-scene"><img class="fishing-background" src="${new URL('../../pesca.png',import.meta.url)}" alt="Un allenatore pesca sulla riva del lago">${biting?`<button type="button" class="bite-target" data-action="pull" aria-label="Tira la lenza e inizia la battaglia"><img src="${new URL('../../esclamativo.png',import.meta.url)}" alt=""></button>`:''}</div>${biting?`<h2>Ha abboccato!</h2><p>Premi il punto esclamativo oppure TIRA! per iniziare la battaglia.</p><p id="countdown"></p>${button('pull','TIRA!',false,'class="primary"')}`:phase==='waiting'?'<h2>Occhi sulla lenza…</h2><p>Aspetta il punto esclamativo, poi premi!</p>':`<h2>Il prossimo record è sotto la superficie.</h2><p>Lancia la lenza e aspetta il punto esclamativo.</p>${button('cast',esc(castLabel),false,'class="primary"')}`}`;}
const statuses={burn:'Scottato',poison:'Avvelenato',sleep:'Addormentato',paralysis:'Paralizzato'};
function fighter(p,wild=false){return `<section class="fighter ${wild?'enemy':'player'}">${wild?fishArt(p.id):artwork(p.id,true)}<div><strong>${esc(p.name)} · Lv. ${p.level}</strong><p>${p.types.map(t=>types[t]).join(' / ')} ${p.status?'· '+statuses[p.status]:''}</p><progress max="${p.maxHp}" value="${p.hp}" aria-label="PS di ${esc(p.name)}"></progress><small>PS ${p.hp} / ${p.maxHp}</small></div></section>`;}
export function FishingBattle(b,chance,busy,showMoves,balls=Infinity){return `<div class="battle"><div class="battle-scene" aria-label="Campo di battaglia sull’acqua">${fighter(b.wild,true)}${fighter(b.player)}</div><div class="battle-actions">${button('moves','LOTTA',busy,'class="primary"')}${button('catch',`CATTURA · ${Math.round(chance*100)}%`,busy||balls<=0)}${button('flee','FUGA',busy)}</div>${showMoves?`<div class="moves">${b.player.moves.map(m=>button('move',`${esc(m.name)}<small>${types[m.type]} · ${m.power||'Stato'} · PP ${m.pp}/${m.maxPp}</small>`,busy||!m.pp,`data-move="${m.id}"`)).join('')}${b.player.moves.every(m=>!m.pp)?button('move','Scontro',busy,'data-move="struggle"'):''}</div>`:''}<p class="hint">Indebolisci il selvatico prima del lancio. Se va KO, non puoi catturarlo.</p>${busy?FishingCatch():''}<ol class="battle-log" aria-label="Diario di lotta">${b.log.map(l=>`<li>${esc(l)}</li>`).join('')}</ol></div>`;}
export function FishingCatch(){return '<div class="catch-animation" role="status"><div class="ball"></div><p>La Poké Ball oscilla…</p></div>';}
export function FishingResult(r,isRecord,limitReached=false,endMessage="Hai catturato 3 Pokémon: gara terminata per oggi."){return `<div class="result"><span class="eyebrow">HAI PESCATO</span>${fishArt(r.species)}<h2>Complimenti! Hai catturato ${FISH[r.species].name}!</h2>${badge(r.rarity)}<div class="metrics"><div><b>${number(r.weight)} kg</b><small>Peso</small></div><div><b>${number(r.length)} m</b><small>Dimensione</small></div><div><b>${r.rating}</b><small>Valutazione · ${number(r.multiplier)}×</small></div><div><b>${r.level}</b><small>Livello</small></div></div>${isRecord?'<p class="record-banner">Nuovo record personale!</p>':''}${limitReached?`<p>${esc(endMessage)}</p>`:button('again','PESCA ANCORA',false,'class="primary"')}${button('end','TERMINA LA GARA')}</div>`;}
export function RecordView(r){return `<h2>Record personale della Gara di Pesca</h2>${r?`<div class="record">${fishArt(r.species)}<div><h3>${FISH[r.species].name}</h3><strong>${number(r.length)} m · ${number(r.weight)} kg</strong><p>${esc(r.rating)} · ${new Date(r.date).toLocaleDateString('it-IT')}</p></div></div>`:'<p>Il tuo primo grande pescato ti aspetta.</p>'}`;}

export function FishingLeaderboard(rows,error,loading){return `<h2>Classifica della pesca · oggi</h2><p>Il Pokémon più lungo di ogni allenatore. A parità di lunghezza, stessa posizione.</p>${button('refresh-ranking',loading?'Aggiornamento…':'Aggiorna classifica',loading)}${error?`<p role="status">${esc(error)}</p>`:loading?'<p>Caricamento classifica…</p>':rows.length?`<ol class="fishing-ranking">${rows.map(r=>`<li class="${r.is_me?'my-ranking':''}"><b>${esc(r.rank_no)}°</b><span>${esc(r.trainer_name)}${r.is_me?' · Tu':''}<small>${esc(FISH[r.pokemon]?.name||r.pokemon)}</small></span><strong>${number(Number(r.length_m))} m</strong></li>`).join('')}</ol>`:'<p>Nessuna cattura in classifica oggi. Il primo posto ti aspetta!</p>'}`;}
