-- Pokéathlon del sabato: una sola puntata, corsa globale alle 17:00.
create table if not exists public.pokeathlon_settings(id boolean primary key default true check(id),test_mode boolean not null default true);
insert into public.pokeathlon_settings values(true,true) on conflict(id) do update set test_mode=true;
create table if not exists public.pokeathlon_races(id uuid primary key default gen_random_uuid(),race_date date unique not null,status text not null default 'betting' check(status in('betting','finished')),winner text,created_at timestamptz default now(),finished_at timestamptz);
create table if not exists public.pokeathlon_bets(id uuid primary key default gen_random_uuid(),race_id uuid not null references public.pokeathlon_races(id) on delete cascade,trainer_id uuid not null references public.profiles(id),pokemon text not null,stake bigint not null check(stake>0),odds numeric(5,2) not null,payout bigint not null default 0,bet_transaction_id uuid unique references public.transactions(id),payout_transaction_id uuid unique references public.transactions(id),created_at timestamptz default now(),unique(race_id,trainer_id));
alter table public.pokeathlon_races enable row level security;alter table public.pokeathlon_bets enable row level security;
drop policy if exists pokeathlon_races_read on public.pokeathlon_races;drop policy if exists pokeathlon_bets_read on public.pokeathlon_bets;
create policy pokeathlon_races_read on public.pokeathlon_races for select to authenticated using(true);
create policy pokeathlon_bets_read on public.pokeathlon_bets for select to authenticated using(trainer_id=public.my_profile_id() or public.is_admin());
grant select on public.pokeathlon_races,public.pokeathlon_bets to authenticated;

create or replace function public.ensure_pokeathlon_race() returns public.pokeathlon_races language plpgsql security definer set search_path=public as $$
declare d date:=(now() at time zone 'Europe/Rome')::date;t boolean;r public.pokeathlon_races;
begin select test_mode and public.is_admin() into t from public.pokeathlon_settings where id=true;if not coalesce(t,false) then d:=d+((6-extract(dow from d)::int+7)%7);end if;insert into public.pokeathlon_races(race_date) values(d) on conflict(race_date) do update set race_date=excluded.race_date returning * into r;return r;end$$;

create or replace function public.get_pokeathlon_status() returns table(race_id uuid,race_date date,status text,winner text,can_bet boolean,my_pokemon text,my_stake bigint,my_payout bigint,current_balance bigint)
language plpgsql security definer set search_path=public as $$
declare r public.pokeathlon_races;p public.profiles;b public.pokeathlon_bets;t boolean;local_now timestamp:=(now() at time zone 'Europe/Rome');
begin r:=public.ensure_pokeathlon_race();select * into p from public.profiles where user_id=auth.uid() and is_active;select test_mode and public.is_admin() into t from public.pokeathlon_settings where id=true;select * into b from public.pokeathlon_bets where pokeathlon_bets.race_id=r.id and trainer_id=p.id;race_id:=r.id;race_date:=r.race_date;status:=r.status;winner:=r.winner;can_bet:=r.status='betting' and b.id is null and (coalesce(t,false) or (local_now::date=r.race_date and local_now<r.race_date::timestamp+time '16:55'));my_pokemon:=b.pokemon;my_stake:=b.stake;my_payout:=b.payout;current_balance:=p.balance;return next;end$$;

create or replace function public.place_pokeathlon_bet(p_pokemon text,p_stake bigint,p_operation_id uuid) returns bigint language plpgsql security definer set search_path=public as $$
declare r public.pokeathlon_races;p public.profiles;o numeric;tx public.transactions;t boolean;local_now timestamp:=(now() at time zone 'Europe/Rome');
begin r:=public.ensure_pokeathlon_race();select * into p from public.profiles where user_id=auth.uid() and is_active for update;select test_mode and public.is_admin() into t from public.pokeathlon_settings where id=true;if r.status<>'betting' or (not coalesce(t,false) and (local_now::date<>r.race_date or local_now>=r.race_date::timestamp+time '16:55')) then raise exception 'BETTING_CLOSED';end if;if exists(select 1 from public.pokeathlon_bets where race_id=r.id and trainer_id=p.id) then raise exception 'ALREADY_BET';end if;if p_stake<1 or p_stake>p.balance then raise exception 'INVALID_STAKE';end if;o:=case p_pokemon when 'Rapidash' then 1.25 when 'Dodrio' then 1.75 when 'Arcanine' then 2.25 when 'Tauros' then 3.5 when 'Raticate' then 6.5 end;if o is null then raise exception 'INVALID_POKEMON';end if;update public.profiles set balance=balance-p_stake,updated_at=now() where id=p.id returning balance into p.balance;insert into public.transactions(operation_id,sender_id,amount,description,transaction_type,created_by) values(p_operation_id,p.id,p_stake,'Puntata Pokéathlon: '||p_pokemon,'admin_debit',p.id) returning * into tx;insert into public.pokeathlon_bets(race_id,trainer_id,pokemon,stake,odds,bet_transaction_id) values(r.id,p.id,p_pokemon,p_stake,o,tx.id);return p.balance;end$$;

create or replace function public.finish_pokeathlon_race(p_force boolean default false) returns text language plpgsql security definer set search_path=public as $$
declare r public.pokeathlon_races;x numeric:=random();w text;b public.pokeathlon_bets;pay bigint;tx public.transactions;t boolean;local_now timestamp:=(now() at time zone 'Europe/Rome');
begin r:=public.ensure_pokeathlon_race();select test_mode into t from public.pokeathlon_settings where id=true;if p_force and not public.is_admin() then raise exception 'FORBIDDEN';end if;if r.status='finished' then return r.winner;end if;if not p_force and local_now<r.race_date::timestamp+time '17:00' then return null;end if;w:=case when x<.35 then 'Rapidash' when x<.60 then 'Dodrio' when x<.80 then 'Arcanine' when x<.93 then 'Tauros' else 'Raticate' end;update public.pokeathlon_races set status='finished',winner=w,finished_at=now() where id=r.id;for b in select * from public.pokeathlon_bets where race_id=r.id and pokemon=w loop pay:=floor(b.stake*b.odds);update public.profiles set balance=balance+pay,updated_at=now() where id=b.trainer_id;insert into public.transactions(operation_id,receiver_id,amount,description,transaction_type,created_by) values(gen_random_uuid(),b.trainer_id,pay,'Vincita Pokéathlon: '||w,'admin_credit',b.trainer_id) returning * into tx;update public.pokeathlon_bets set payout=pay,payout_transaction_id=tx.id where id=b.id;end loop;return w;end$$;

create or replace function public.admin_reset_pokeathlon() returns boolean language plpgsql security definer set search_path=public as $$
declare r public.pokeathlon_races;b public.pokeathlon_bets;p public.profiles;
begin if not public.is_admin() then raise exception 'FORBIDDEN';end if;r:=public.ensure_pokeathlon_race();for b in select * from public.pokeathlon_bets where race_id=r.id loop select * into p from public.profiles where id=b.trainer_id for update;if b.payout>p.balance then raise exception 'RESET_BALANCE_CONFLICT';end if;if b.payout>0 then update public.profiles set balance=balance-b.payout,updated_at=now() where id=p.id;insert into public.transactions(operation_id,sender_id,amount,description,transaction_type,created_by) values(gen_random_uuid(),p.id,b.payout,'Reset vincita Pokéathlon','admin_debit',public.my_profile_id());end if;update public.profiles set balance=balance+b.stake,updated_at=now() where id=p.id;insert into public.transactions(operation_id,receiver_id,amount,description,transaction_type,created_by) values(gen_random_uuid(),p.id,b.stake,'Rimborso reset Pokéathlon','admin_credit',public.my_profile_id());end loop;delete from public.pokeathlon_races where id=r.id;return true;end$$;
revoke all on function public.ensure_pokeathlon_race(),public.get_pokeathlon_status(),public.place_pokeathlon_bet(text,bigint,uuid),public.finish_pokeathlon_race(boolean),public.admin_reset_pokeathlon() from public;
grant execute on function public.get_pokeathlon_status(),public.place_pokeathlon_bet(text,bigint,uuid),public.finish_pokeathlon_race(boolean),public.admin_reset_pokeathlon() to authenticated;
create extension if not exists pg_cron;do $$begin if not exists(select 1 from cron.job where jobname='finish-pokeathlon') then perform cron.schedule('finish-pokeathlon','*/5 * * * *','select public.finish_pokeathlon_race(false);');end if;end$$;
