import {RULES,FOSSILS,fresh,itemName,price,startExcavation,settleExcavation,sell,revive,finishBattle,demoKit,needsBuriedFossil} from './model.mjs?v=rewards-4';
import {createPokemon,artwork,types} from '../starter/starter-ui.js?v=icons-2';
import {turn} from './battle.mjs';
const account=new URLSearchParams(location.search).get('account')||'guest';
const KEY='champion:fossils-beta:v1:'+account,catalog=await fetch('./catalog.json').then(r=>{if(!r.ok)throw Error('Catalogo non disponibile');return r.json();});
const byId=new Map(catalog.map(i=>[i.id,i]));let state=fresh(),tab=new URLSearchParams(location.search).get('tab')==='lab'?'lab':'mining',filter='all',ready=false,busy=false,notice='',lastLoot=null;
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved?.version===1&&saved.inventory&&Number.isFinite(saved.balance))state=saved;}catch{}
state.monday=true;
if(state.pendingMining){state.pendingMining=null;notice='Lo scavo precedente è stato interrotto. Il tentativo resta consumato; puoi iniziare un nuovo scavo.';}
const $=s=>document.querySelector(s),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch{notice='La memoria del browser non è disponibile: questa prova durerà solo fino alla chiusura della pagina.';}}
function itemArt(item){return `<span class="artifact"><span style="width:${item.w*16}px;height:${item.h*16}px;background-image:url('./mining/assets/object_sheet.png');background-position:-${item.x*16}px -${item.y*16}px;background-size:1024px 1024px"></span></span>`;}
function pokemonArt(id,back=false){if(['kabuto','omanyte','aerodactyl','bulbasaur','squirtle','charmander'].includes(id))return artwork(id,back);return `<img src="./assets/${id}.png" alt="${esc(id)}" width="144" height="144">`;}
function render(){
 $('#wallet').textContent=state.balance+' ₽ · '+(state.xp||0)+' XP';$('#message').textContent=notice;$('#demo-starter').value=state.starter;$('#demo-starter').disabled=!!state.battle;
 document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false'));document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==tab);
 $('#mining-count').textContent=`${Math.max(0,RULES.excavationLimit-state.attempts)} / 3 scavi di prova disponibili`;
 $('#dig-start').hidden=!!state.pendingMining;
 $('#dig-start').innerHTML=`<div class="dig-hero"><span aria-hidden="true">⛏</span><h3>Cosa nasconde la parete?</h3><p>Tocca le rocce per scavare. I reperti finiscono nello Zaino al termine dello scavo.</p><button class="primary" data-action="dig" ${!ready||state.attempts>=3||state.balance<50?'disabled':''}>${ready?'Inizia scavo · 50 ₽':'Preparazione dello scavo…'}</button></div>`;
 $('#mining-frame').hidden=!state.pendingMining;
 $('#dig-result').hidden=!lastLoot||!!state.pendingMining;
 if(lastLoot)$('#dig-result').innerHTML=`<h3>${lastLoot.failed?'La parete è crollata':'Scavo completato!'}</h3><p>${lastLoot.items.length?'Reperti aggiunti allo Zaino:':'Non sei riuscito a liberare completamente un reperto.'}</p><div class="loot-strip">${lastLoot.items.map(id=>`<span>${itemArt(byId.get(id))}${esc(itemName(byId.get(id)))}</span>`).join('')}</div><button data-tab="bag">Apri lo Zaino →</button>`;
 const entries=catalog.filter(i=>(state.inventory[i.id]||0)>0),visible=entries.filter(i=>filter==='all'||(filter==='fossils')===!!FOSSILS[i.id]);
 $('#bag').innerHTML=`<div class="section-head"><div><span class="eyebrow">I TUOI RITROVAMENTI</span><h2>Lo Zaino</h2><p>Vendi gli oggetti che non ti servono oppure porta un fossile al laboratorio.</p></div><div class="pill">${entries.reduce((s,i)=>s+state.inventory[i.id],0)} oggetti</div></div><div class="filters">${[['all','Tutti'],['fossils','Fossili'],['other','Altri oggetti']].map(([id,label])=>`<button data-filter="${id}" aria-pressed="${filter===id}">${label}</button>`).join('')}</div><div class="item-grid">${visible.length?visible.map(i=>`<article class="panel item-card">${itemArt(i)}<div><span class="tag">${FOSSILS[i.id]?'Fossile':'Reperto'}</span><h3>${esc(itemName(i))}</h3><p>Quantità: <b>${state.inventory[i.id]}</b> · Vendita: <b>${price(i)} ₽</b> ciascuno</p>${FOSSILS[i.id]?`<p>Risveglia ${FOSSILS[i.id].pokemon}</p>`:''}<div class="item-actions"><button data-action="sell" data-id="${esc(i.id)}">Vendi 1 · ${price(i)} ₽</button>${FOSSILS[i.id]?`<button class="primary" data-action="prepare" data-id="${esc(i.id)}" ${state.battle?'disabled':''}>Laboratorio</button>`:''}</div></div></article>`).join(''):'<article class="panel empty"><h3>Nessun reperto qui, per ora.</h3><p>Inizia uno scavo o usa il kit nei comandi della beta.</p><button data-tab="mining">Vai ai sotterranei</button></article>'}</div>`;
 renderLab();
}
function fighter(p,isPlayer){return `<div class="fighter ${isPlayer?'player':'enemy'}"><div class="fighter-info"><h3>${p.name} <small>Lv. ${p.level}</small></h3><p>${p.types.map(t=>types[t]).join(' / ')}</p><meter min="0" max="${p.maxHp}" value="${p.hp}">${p.hp}</meter><small>${p.hp} / ${p.maxHp} PS${p.status?' · '+p.status:''}</small></div><div class="pokemon-art">${pokemonArt(p.id,isPlayer)}</div></div>`;}
function renderLab(){
 const owned=Object.entries(FOSSILS).filter(([id])=>state.inventory[id]>0),b=state.battle;
 $('#lab').innerHTML=`<div class="section-head"><div><span class="eyebrow">RICERCA SUL PASSATO</span><h2>Laboratorio Fossili</h2><p>Un fossile può tornare in vita. Preparati ad affrontare il Pokémon che risveglierai. Vittoria: <b>+${RULES.victoryMoney} ₽ e +${RULES.victoryXp} XP</b>.</p></div><div class="pill">Risveglio gratuito · 1 fossile</div></div>${b?`<div class="battle-layout"><article class="panel battle"><div class="arena">${fighter(b.wild,false)}${fighter(b.player,true)}</div><div class="moves">${b.player.moves.map(m=>`<button data-action="move" data-id="${m.id}" ${busy||m.pp<=0?'disabled':''}><b>${m.name}</b><small>${types[m.type]} · PP ${m.pp}/${m.maxPp}</small></button>`).join('')}${b.player.moves.every(m=>m.pp<=0)?'<button data-action="move" data-id="struggle">Scontro</button>':''}</div><button data-action="flee" ${busy?'disabled':''}>Abbandona la battaglia</button></article><aside class="panel battle-log"><h3>Diario di ricerca</h3><ol>${b.log.map(l=>`<li>${esc(l)}</li>`).join('')||'<li>Il fossile si è risvegliato! Scegli una mossa.</li>'}</ol><p class="muted">Battaglia di prova. Il fossile è già consumato; puoi uscire e riprendere qui.</p></aside></div>`:`${state.result?`<article class="panel result ${state.result.outcome==='win'?'win':''}"><span class="eyebrow">RICERCA CONCLUSA</span><h3>${state.result.outcome==='win'?'Hai vinto contro '+FOSSILS[state.result.fossil].pokemon+'!':state.result.outcome==='loss'?'Il tuo Starter è esausto.':'Hai interrotto la battaglia.'}</h3><p>${state.result.outcome==='win'?(state.result.reward?`Premio accreditato: +${state.result.reward.money} Pokédollari e +${state.result.reward.xp} XP.`:'Vittoria registrata prima dell’introduzione dei premi.'):'Il fossile è stato utilizzato per il risveglio. Nessun premio per questa battaglia.'}</p></article>`:''}<div class="item-grid">${owned.length?owned.map(([id,f])=>`<article class="panel item-card">${itemArt(byId.get(id))}<div><span class="tag">${esc(f.name)} · ×${state.inventory[id]}</span><h3>${f.pokemon}</h3><p>${f.types.map(t=>types[t]).join(' / ')} · Avversario Lv. 15</p><button class="primary" data-action="prepare" data-id="${id}" >Risveglia e combatti</button></div></article>`).join(''):'<article class="panel empty"><h3>Ti serve un fossile.</h3><p>Puoi trovarlo nella Caccia ai Fossili o aggiungere il kit di esempio per provare.</p><button data-tab="mining">Vai ai sotterranei</button></article>'}</div>`}`;
}
function prepare(id){if(state.battle)throw Error('Hai già una battaglia in corso.');if(!(state.inventory[id]>0))throw Error('Fossile non disponibile.');const f=FOSSILS[id];if(!f)throw Error('Seleziona un fossile.');const dialog=document.createElement('dialog');dialog.innerHTML=`<h2>Risvegliare ${f.pokemon}?</h2><p>Il risveglio è <b>gratuito</b>: usi solo <b>1 ${f.name}</b>. Il fossile viene consumato all’avvio, anche se perdi o abbandoni.</p><p>Combatti con il tuo ${state.starter} di prova al livello 15. Se vinci ricevi <b>${RULES.victoryMoney} Pokédollari e ${RULES.victoryXp} XP</b>.</p><div class="dialog-actions"><button data-cancel>Annulla</button><button class="primary" data-confirm>Risveglia e avvia battaglia</button></div>`;document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.querySelector('[data-confirm]').onclick=()=>{try{const wild=createPokemon('squirtle',{level:15,moves:f.moves});const values=f.base.map((base,i)=>Math.floor((2*base+31)*15/100)+(i===0?25:5));Object.assign(wild,{id:f.species,name:f.pokemon,types:f.types,maxHp:values[0],hp:values[0],baseHp:values[0],stats:Object.fromEntries(['atk','def','spa','spd','spe'].map((k,i)=>[k,values[i+1]]))});revive(state,id,{player:createPokemon(state.starter,{level:15}),wild,turn:0,log:[]});tab='lab';notice=f.pokemon+' si è risvegliato!';persist();dialog.close();render();}catch(error){notice=error.message;dialog.close();render();}};dialog.showModal();}
function finish(outcome){finishBattle(state,outcome);}
document.addEventListener('click',async event=>{const button=event.target.closest('button');if(!button||button.disabled)return;try{
 if(button.dataset.tab){tab=button.dataset.tab;notice='';render();return;}if(button.dataset.filter){filter=button.dataset.filter;render();return;}
 const action=button.dataset.action,id=button.dataset.id;
 if(action==='dig'){startExcavation(state,crypto.randomUUID());lastLoot=null;notice=needsBuriedFossil(state)?'In questa parete è nascosto almeno un fossile. Devi liberarlo completamente prima del crollo.':'Scavo iniziato. Scegli dove colpire la roccia.';persist();render();$('#mining-frame').contentWindow.postMessage({channel:'fossil-demo',type:'start',session:state.pendingMining,guaranteeFossil:needsBuriedFossil(state)},location.origin);}
 if(action==='sell'){const value=sell(state,id,1,catalog);notice=`Venduto 1 ${itemName(byId.get(id))}: +${value} ₽.`;persist();render();}
 if(action==='prepare')prepare(id);
 if(action==='kit'){demoKit(state);notice='Kit di esempio aggiunto allo Zaino.';tab='bag';persist();render();}
 if(action==='refill'){if(state.pendingMining)throw Error('Concludi prima lo scavo.');state.attempts=0;state.fossilRecoveredThisBatch=false;state.balance=Math.max(state.balance,500);notice='Nuovi tentativi e saldo di prova disponibili. I reperti sono conservati.';persist();render();}
 if(action==='reset'){if(!confirm('Azzerare saldo, reperti e battaglie della beta?'))return;state=fresh();persist();location.reload();}
 if(action==='move'&&state.battle&&!busy){const battle=state.battle;if(id!=='struggle'&&!battle.player.moves.some(m=>m.id===id&&m.pp>0))return;busy=true;renderLab();const outcome=turn(battle,id);if(outcome)finish(outcome==='wildKO'?'win':'loss');persist();await new Promise(r=>setTimeout(r,450));busy=false;render();}
 if(action==='flee'&&state.battle&&!busy&&confirm('Abbandonare? Il fossile utilizzato non viene restituito.')){finish('flee');persist();render();}
 }catch(error){busy=false;notice=error.message;render();}});

$('#demo-starter').addEventListener('change',event=>{if(!state.battle){state.starter=event.target.value;persist();render();}});
window.addEventListener('message',event=>{if(event.origin!==location.origin||event.source!==$('#mining-frame').contentWindow||event.data?.channel!=='fossil-demo')return;const data=event.data;if(data.type==='ready'){ready=true;render();}if(data.type==='settled'){try{if(settleExcavation(state,data.session,data.items,catalog)){lastLoot=data;notice=data.items.length?`${data.items.length} reperti recuperati e aggiunti allo Zaino.`:'Scavo concluso senza reperti recuperati.';persist();render();}}catch(error){notice=error.message;render();}}});
// The frame can finish loading before the catalog fetch: reload once listeners exist.
$('#mining-frame').src='./mining/index.html?v=buried-fossil-2';
persist();render();
