import {listPokemon,getPokemonById,getMoveById,evolutionChain,evolutionMethod,typeNames} from './data.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=p=>'#'+String(p.id).padStart(3,'0');
const sprite=(p,back=false,lazy=true)=>`<span class="pokemon-sprite-box"><img src="${esc(p.sprites[back?'back':'front'])}" alt="${esc(p.name)}${back?' di spalle':''}" loading="${lazy?'lazy':'eager'}"></span>`;
const types=p=>p.types.map(t=>`<span class="tag">${typeNames[t]||esc(t)}</span>`).join(' ');
const growthNames={fast:'Rapida',medium_fast:'Medio-rapida',medium_slow:'Medio-lenta',slow:'Lenta',slightly_fast:'Leggermente rapida',slightly_slow:'Leggermente lenta'};
export function mountPokedex(host){
 const root=host.attachShadow({mode:'open'});let current=null,moveTab='levelUp';
 root.innerHTML=`<link rel="stylesheet" href="${new URL('./style.css',import.meta.url)}"><main><a href="#dashboard">← Home</a><p class="eyebrow">POKÉMON CRYSTAL · GENERAZIONI I E II</p><h1>Pokédex</h1><p>Da Bulbasaur a Celebi: scopri specie, evoluzioni e mosse.</p><div class="filters"><label>Cerca Pokémon<input type="search" placeholder="Nome o numero, es. Pikachu o 025" autocomplete="off"></label><label>Generazione<select data-generation><option value="">Tutti</option><option value="1">Generazione 1</option><option value="2">Generazione 2</option></select></label><label>Tipo<select data-type><option value="">Tutti i tipi</option>${Object.entries(typeNames).map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}</select></label></div><p data-count role="status"></p><div class="cards"></div><dialog aria-labelledby="dex-detail-title"><button class="close" aria-label="Chiudi scheda">✕ Chiudi</button><div data-detail></div></dialog></main>`;
 const dialog=root.querySelector('dialog');
 function renderList(){const list=listPokemon({query:root.querySelector('input').value,generation:root.querySelector('[data-generation]').value,type:root.querySelector('[data-type]').value});root.querySelector('[data-count]').textContent=list.length+' Pokémon';root.querySelector('.cards').innerHTML=list.map(p=>`<button class="card" data-pokemon="${p.id}" aria-label="Apri ${number(p)} ${esc(p.name)}"><span class="muted">${number(p)} · Gen. ${p.generation}</span>${sprite(p)}<strong>${esc(p.name)}</strong><span class="types">${types(p)}</span></button>`).join('')||'<p>Nessun Pokémon trovato. Prova un altro nome o filtro.</p>';}
 function renderMoves(){const entries=current.learnset[moveTab]||[];root.querySelector('[data-moves]').innerHTML=entries.length?`<div class="table-scroll"><table><thead><tr>${moveTab==='levelUp'?'<th>Lv.</th>':''}<th>Mossa</th><th>Tipo</th><th>Potenza</th><th>Precisione</th><th>PP</th><th>Categoria</th></tr></thead><tbody>${entries.map(entry=>{const key=typeof entry==='string'?entry:entry.move,m=getMoveById(key);if(!m)return '';return `<tr>${moveTab==='levelUp'?`<td>${entry.level}</td>`:''}<td>${esc(m.name)}</td><td>${typeNames[m.type]}</td><td>${m.power||'—'}</td><td>${m.accuracy??'—'}</td><td>${m.pp}</td><td>${{physical:'Fisica',special:'Speciale',status:'Stato'}[m.category]}</td></tr>`;}).join('')}</tbody></table></div>`:'<p>Nessuna mossa prevista in questa categoria.</p>';root.querySelectorAll('[data-move-tab]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.moveTab===moveTab));}
 function detail(id){current=getPokemonById(id);if(!current)return;moveTab='levelUp';const p=current,edges=evolutionChain(id),gender=p.gender,stats={hp:'PS',attack:'Attacco',defense:'Difesa',spAttack:'Attacco Speciale',spDefense:'Difesa Speciale',speed:'Velocità'};
 root.querySelector('[data-detail]').innerHTML=`<p class="eyebrow">${number(p)} · Generazione ${p.generation}</p><h2 id="dex-detail-title">${esc(p.name)}</h2><div class="sprites"><figure>${sprite(p,false,false)}<figcaption>Fronte</figcaption></figure><figure>${sprite(p,true,false)}<figcaption>Retro</figcaption></figure></div><div class="types">${types(p)}</div><h3>Statistiche base</h3><div class="stats">${Object.entries(stats).map(([key,label])=>`<div><span>${label}</span><meter min="0" max="255" value="${p.baseStats[key]}" aria-label="${label}"></meter><b>${p.baseStats[key]}</b></div>`).join('')}</div><h3>Altri dati</h3><dl>${Object.entries({'Base EXP':p.baseExp,'Catch Rate':p.catchRate,'Crescita EXP':growthNames[p.growth]||p.growth,'Sesso':(gender.genderless||gender.femalePercent===null&&gender.malePercent===null)?'Senza sesso':`♀ ${gender.femalePercent}% · ♂ ${gender.malePercent}%`,'Cicli schiusa':p.hatchCycles,'Gruppi uovo':[...new Set(p.eggGroups)].join(', ')}).map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl><h3>Catena evolutiva</h3><div class="evolutions">${edges.length?edges.map(e=>`<article><button data-pokemon="${e.from.id}">${sprite(e.from)}${esc(e.from.name)}</button><p>→ ${esc(evolutionMethod(e))}</p><button data-pokemon="${e.to}">${sprite(e.pokemon)}${esc(e.pokemon.name)}</button></article>`).join(''):'<p>Nessuna evoluzione in Pokémon Crystal.</p>'}</div><h3>Mosse</h3><nav class="move-tabs" aria-label="Apprendimento mosse">${[['levelUp','LIVELLO'],['machine','TM/HM'],['egg','UOVO']].map(([key,label])=>`<button data-move-tab="${key}">${label}</button>`).join('')}</nav><div data-moves></div>`;renderMoves();if(!dialog.open)dialog.showModal();dialog.scrollTop=0;}
 root.addEventListener('input',e=>{if(e.target.matches('input'))renderList();});root.addEventListener('change',e=>{if(e.target.matches('select'))renderList();});
 root.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.pokemon)detail(b.dataset.pokemon);if(b.classList.contains('close'))dialog.close();if(b.dataset.moveTab){moveTab=b.dataset.moveTab;renderMoves();}});
 dialog.addEventListener('close',()=>{if(dialog.open)return;root.querySelector('[data-detail]').replaceChildren();current=null;});
 root.addEventListener('error',e=>{if(e.target.tagName==='IMG'){e.target.removeAttribute('src');e.target.alt='Sprite non disponibile';}},{capture:true});
 if(!listPokemon().length){root.querySelector('[data-count]').textContent='Database non disponibile. Ricarica la pagina.';}else renderList();
}
