import {loadTrainerAtlas} from './assets.mjs';
import {RouteMap} from './map.mjs?v=1';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const messages={ROUTE_NOT_INSTALLED:'Route 01 deve essere installata su Supabase: controlla la migrazione SQL e la Edge Function route01.',NOT_AUTHORIZED:'Accesso non autorizzato.',STATION_BUSY:'Allenatore impegnato in una lotta o posto riservato al vincitore.',STATION_LOCKED:'Supera prima la postazione precedente.',ROUTE_CLOSED:'Le nuove sfide sono temporaneamente chiuse.',BATTLE_ACTIVE:'Hai già una battaglia da riprendere.',STARTER_REQUIRED:'Scegli prima il tuo starter in La mia squadra.',INSUFFICIENT_BALANCE:'Saldo disponibile insufficiente.',OWN_STATION:'Questo posto è tuo: puoi proseguire.',PAIR_DAILY_LIMIT:'Hai già disputato una sfida con posta con questo allenatore oggi.',PASS_NOT_ALLOWED:'Per superare la tappa devi aver vinto contro questo allenatore.',DEFENSE_ACTIVE:'La tua copia sta difendendo: attendi la fine prima di cambiare posto, aggiornare o ritirarti.',RESERVATION_EXPIRED:'La prenotazione di 60 secondi è scaduta.',NOT_OWNER:'Questa postazione non ti appartiene.',STALE_BATTLE:'La battaglia è stata aggiornata: ricarico il turno.',STALE_CONFIG:'La configurazione è cambiata. Riapri il modulo prima di salvare.',INVALID_MOVE:'Mossa non disponibile o PP esauriti.',INVALID_SWITCH:'Quel Pokémon non può entrare.',INVALID_TEAM:'Controlla squadra e livelli.',INVALID_MOVES:'Scegli da una a quattro mosse valide.',BLOCKED_POSITION:'Ingresso e allenatori devono trovarsi su caselle percorribili.',INVALID_MAP:'La mappa non è valida.',ROUTE_INCOMPLETE:'Supera tutte e cinque le postazioni prima di ricominciare.',OPERATION_MISMATCH:'Il tentativo non corrisponde all’operazione precedente.'};
export async function mountRoute01(host,{client,userId,test=false,admin=false,profile=false,isCurrent=()=>true,onBalance=()=>{}}){
 const root=host.attachShadow({mode:'open'}),key=`champion:route01:${userId}:${test}`;
 let state,battle,busy=false,pending=null,selected=null,message='',mapView,draftMap,editPosition=1,destroyed=false;
 try{pending=JSON.parse(localStorage.getItem(key));}catch{}
 const current=()=>host.isConnected&&isCurrent();
 const sprites=await fetch(new URL('./sprites.json',import.meta.url)).then(r=>r.json());
 const db=window.ROUTE_POKEMON_DB,moves=window.ROUTE_MOVE_DB,name=p=>db[p.speciesId]?.name||p.speciesId;
 root.innerHTML=`<link rel="stylesheet" href="${new URL('./style.css?v=1',import.meta.url)}"><main><a href="${admin?'#admin':'#dashboard'}">← ${admin?'Admin':'Profilo'}</a><h1>${profile?'Personaggio esplorazione':admin?'Gestione Route 01':'Route 01'}</h1>${test?'<p class="test">MODALITÀ TEST · saldo di prova separato. Squadre e regole sono quelle della Route; nessun movimento di PD reali.</p>':''}<p class="status" role="status"></p><div data-toolbar></div><div data-profile></div>${!profile&&!admin?'<canvas class="map" aria-label="Mappa Route 01"></canvas><div class="controls"><button data-direction="up" aria-label="Su">▲</button><button data-direction="left" aria-label="Sinistra">◀</button><button data-direction="down" aria-label="Giù">▼</button><button data-direction="right" aria-label="Destra">▶</button><button data-interact disabled>Avvicinati a un allenatore</button></div><p>Frecce o WASD per camminare · E / Invio per interagire.</p><div data-summary></div>':''}<div data-admin></div><details><summary>Resoconto e movimenti</summary><div class="history" data-history></div></details></main><dialog><div data-dialog></div></dialog>`;
 const dialog=root.querySelector('dialog'),content=root.querySelector('[data-dialog]');
 dialog.addEventListener('cancel',e=>{if(busy||battle?.status==='active')e.preventDefault();});dialog.addEventListener('close',()=>{selected=null;mapView?.stop();});
 async function request(body){const {data,error}=await client.functions.invoke('route01',{body:{test,...body}});let problem=data?.error;if(error){try{problem=(await error.context?.json())?.error;}catch{}}if(error?.context?.status===404||/Could not find the function|does not exist/.test(problem||''))problem='ROUTE_NOT_INSTALLED';if(error||problem){const e=Error(messages[problem]||'Operazione non confermata. Premi Riprova per recuperare lo stesso tentativo.');e.definitive=!!messages[problem]||/^(INVALID_|BATTLE_ENDED|BATTLE_NOT_INITIALIZED)/.test(problem||'');throw e;}return data;}
 function accept(data){state=data;if(!test)onBalance(data.balance,data.locked);if(data.active)battle=data.active;else if(battle?.status==='active'){const history=data.history.find(b=>b.id===battle.id);if(history?.status==='settled')battle={...battle,...history};}mapView?.setState(data);}
 async function load(){accept(await request({type:'read',admin}));ensureMap();}
 function ensureMap(){if(!profile&&!admin&&!mapView){mapView=new RouteMap(root.querySelector('.map'),{map:state.config.map,sprites,userId,blocked:()=>busy||!!pending||dialog.open,onInteract:openStation,onNear:n=>{const button=root.querySelector('[data-interact]');button.disabled=!n||busy;button.textContent=n?'Interagisci · Posto '+n:'Avvicinati a un allenatore';}});mapView.setState(state);mapView.controls(root);}}
 async function perform(body){
  if(busy)return;busy=true;mapView?.stop();message='';render();
  try{
   if(!pending){const command={...body,test,operationId:crypto.randomUUID()};localStorage.setItem(key,JSON.stringify(command));pending=command;}
   const result=await request(pending),type=pending.type;pending=null;localStorage.removeItem(key);
   if(['start','init','act'].includes(type))battle=result;else if(result.config)accept(result);
   await load();if(battle?.status==='active'||['start','init','act'].includes(type))openBattle();
   if(body.type==='command'&&body.action==='restart'){mapView.position={...state.config.map.entry};dialog.close();}
  }catch(e){message=e.message;if(e.definitive){pending=null;localStorage.removeItem(key);await load().catch(()=>{});}}finally{busy=false;render();}
 }
 const command=(action,args={})=>perform({type:'command',action,args});
 function render(){
  if(!current())return;
  if(!busy&&!pending)root.querySelectorAll('[data-busy-disabled]').forEach(b=>{b.disabled=false;delete b.dataset.busyDisabled;});
  root.querySelector('.status').textContent=busy?'Salvataggio…':message;
  if(!state)return;
  root.querySelector('[data-toolbar]').innerHTML=`<div class="funds"><strong>Disponibili: ${state.balance} PD</strong><span>Bloccati: ${state.locked} PD</span></div>${!state.config.opened&&!test?'<p>Le nuove sfide reali sono chiuse. Puoi esplorare, gestire il tuo posto o riprendere una lotta.</p>':''}<div class="toolbar"><button data-action="refresh">Aggiorna</button>${pending?'<button data-action="retry">Riprova ultima operazione</button>':''}${state.active?'<button data-action="resume">Riprendi battaglia</button>':''}${!admin&&!profile?'<a href="#route01-profile">Scegli personaggio</a><a href="#route01-test">Apri modalità test</a>':''}${state.progress.unlocked===6&&!profile?'<button data-action="restart">Nuova percorrenza</button>':''}</div>`;
  if(profile)renderProfile();
  if(root.querySelector('[data-summary]'))root.querySelector('[data-summary]').innerHTML=`<p>Postazioni sbloccate: ${Math.min(5,state.progress.unlocked)} / 5${state.progress.unlocked===6?' · Percorso completato':''}</p>${state.stations.filter(s=>s.reserved_by===userId).map(s=>`<button data-action="station" data-position="${s.position}">Posto ${s.position}: scegli entro ${Math.max(0,Math.ceil((Date.parse(s.reserved_until)-Date.now())/1000))} secondi</button>`).join('')}`;
  root.querySelector('[data-history]').innerHTML=state.history.map(h=>`<p>Posto ${h.position} · ${esc(h.attacker_name)} contro ${esc(h.defender_name)} · ${h.training?'Allenamento':h.stake+' PD'} · ${esc(h.result||'In corso')} ${esc(h.reason||'')}${h.defender===userId?' · Difesa della tua copia':''} · ${new Date(h.created_at).toLocaleString('it-IT')}${admin&&h.status==='active'?` <button data-action="technical" data-battle="${h.id}">Annulla e rimborsa</button>`:''}</p>`).join('')+state.ledger.map(l=>`<p>${esc(l.reason)} · ${l.amount>0?'+':''}${l.amount} PD${admin?' · '+esc(l.user_name||l.user_id):''}</p>`).join('');
  if(dialog.open){if(battle&&content.dataset.kind==='battle')renderBattle();else if(selected)renderStation();}
  if(dialog.open&&pending)content.insertAdjacentHTML('afterbegin','<button data-action="retry">Riprova ultima operazione</button>');
  if(dialog.open&&message)content.insertAdjacentHTML('afterbegin','<p role="alert" class="status">'+esc(message)+'</p>');
  if(busy||pending)root.querySelectorAll('button,input,select,textarea').forEach(b=>{if((busy||b.dataset.action!=='retry')&&!b.disabled){b.dataset.busyDisabled='true';b.disabled=true;}});
 }
 function renderProfile(){root.querySelector('[data-profile]').innerHTML=`<p>Scegli il personaggio per l’esplorazione e le nuove copie difensive.</p><div class="sprite-options">${Object.entries(sprites.sprites).map(([id,s])=>`<button data-action="sprite" data-sprite="${id}" aria-pressed="${state.sprite===id}"><canvas class="sprite-preview" data-preview="${id}" width="64" height="64"></canvas>${esc(s.name)}${state.sprite===id?' ✓':''}</button>`).join('')}</div>`;loadTrainerAtlas(sprites).then(img=>root.querySelectorAll('[data-preview]').forEach(c=>{const r=sprites.sprites[c.dataset.preview].down[1],ctx=c.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.drawImage(img,r.x,r.y,r.w,r.h,0,0,64,64);})).catch(()=>{});}
 function teamHTML(team){return `<div class="team">${team.map(p=>`<article><img src="${esc(db[p.speciesId]?.sprites.front)}" alt=""><b>${esc(name(p))}</b><small>Lv. ${p.level}</small></article>`).join('')}</div>`;}
 function show(){mapView?.stop();if(!dialog.open)dialog.showModal();}
 function openStation(position){selected=position;content.dataset.kind='station';renderStation();show();}
 function renderStation(){const s=state.stations.find(s=>s.position===selected);if(!s)return;const own=s.owner_id===userId,training=!s.owner_id&&s.dailyWins>=s.rules.daily_limit,reserved=s.reserved_by===userId,locked=selected>state.progress.unlocked,missing=Math.max(0,s.effectiveStake-state.balance),blocked=s.battle_id||s.reserved_by;
  content.innerHTML=`<h2>Posto ${s.position} · ${esc(s.owner_name||s.rules.bot_name)}</h2>${teamHTML(s.displayTeam)}<p>Posta: ${s.effectiveStake} PD · Difese consecutive: ${s.wins}</p>${training?'<p class="test">Allenamento: premio giornaliero già riscosso. Nessuna posta, premio o conquista.</p>':`<p>${s.owner_id?'Sfida contro la copia salvata di questo allenatore, anche offline.':'Premio bot: '+s.rules.reward+' PD · '+s.rules.daily_limit+' vittorie premiate al giorno.'}</p>`}${s.reset_pending?'<p>Reset richiesto: verrà completato al termine della difesa.</p>':''}${reserved?`<p>Hai vinto! Prenotazione valida fino alle ${new Date(s.reserved_until).toLocaleTimeString('it-IT')}. Per occupare il posto depositerai ${s.reservation_stake} PD.</p><div class="actions"><button data-action="occupy">Occupa questo posto</button><button data-action="proceed">Prosegui</button></div>`:own?`<p>Il tuo deposito è bloccato. La copia non cambia finché non la aggiorni.</p><div class="actions"><button data-action="pass">Prosegui</button><button data-action="update" ${s.battle_id?'disabled':''}>Aggiorna copia squadra</button><button data-action="withdraw" ${s.battle_id?'disabled':''}>Ritirati · recupera ${s.deposit} PD</button></div>`:`${locked?'<p>Supera la postazione precedente.</p>':s.pair?`<p>Una sfida con posta per coppia al giorno.</p>${s.pair.winner===userId?'<button data-action="pass">Supera la tappa · già vinta oggi</button>':'<p>Potrai riprovare domani.</p>'}`:`${!training&&blocked?'<p>Allenatore impegnato in una lotta o posto riservato.</p>':''}${!training&&missing?'<p>Mancano '+missing+' PD disponibili. Il progresso è conservato.</p>':''}<button class="primary" data-action="challenge" ${(!training&&(blocked||missing))||state.active?'disabled':''}>${training?'Inizia allenamento':'Sfida · deposita '+s.effectiveStake+' PD'}</button>`}`}
  <button data-action="close">Torna alla mappa</button>`;
 }
 function openBattle(){if(mapView&&battle){const target=state.config.map.stations[battle.position-1];if(Math.hypot(target.x-mapView.position.x,target.y-mapView.position.y)>40){for(const [dx,dy] of [[0,24],[0,-24],[24,0],[-24,0]])if(mapView.canWalk(target.x+dx,target.y+dy)){mapView.position={x:target.x+dx,y:target.y+dy};break;}}}content.dataset.kind='battle';renderBattle();show();}
 function renderBattle(){if(!battle)return;
  if(battle.status==='settled'){content.innerHTML=`<h2>${({win:'Vittoria!',loss:'Sconfitta',draw:'Pareggio / annullamento'})[battle.result]||'Battaglia conclusa'}</h2><p>${battle.training?'Allenamento concluso: nessuna variazione di saldo.':battle.result==='win'?'Posta restituita e premio accreditato.':battle.result==='loss'?'La posta è stata persa.':'La posta dello sfidante è stata restituita.'}</p><p>Saldo disponibile: ${state.balance} PD · Bloccati: ${state.locked} PD.</p>${state.stations.some(s=>s.reserved_by===userId&&s.position===battle.position)?`<button data-action="station" data-position="${battle.position}">Occupa questo posto o prosegui</button>`:''}<button data-action="close">Torna alla mappa</button>`;return;}
  const st=battle.state;if(!st){content.innerHTML='<h2>Incontro prenotato</h2><p>La posta è protetta dal server. Prepara le squadre per iniziare o riprendere.</p><button data-action="init">Apri battaglia</button>';return;}
  const p=st.party[st.activeIndex],e=st.defenders[st.defenderIndex],hp=p=>p.routeStats?.maxHp||window.RoutePokemonCore.maxHp(p),available=p.moves.filter(k=>(p.pp[k]||0)>0),keys=available.length?p.moves:['STRUGGLE'];
  content.innerHTML=`<h2>${battle.training?'Allenamento':'Sfida'} · Posto ${battle.position}</h2><p>Turno ${st.turn} · Nessuna EXP · PS e PP del profilo invariati</p><b>${esc(name(e))} · Lv. ${e.level} · ${e.currentHp}/${hp(e)} PS</b><progress max="${hp(e)}" value="${e.currentHp}"></progress><small>Difensori rimasti: ${st.defenders.filter(m=>m.currentHp>0).length}/${st.defenders.length}</small><div class="battle-scene"><img src="${esc(db[p.speciesId].sprites.back)}" alt="${esc(name(p))}"><img src="${esc(db[e.speciesId].sprites.front)}" alt="${esc(name(e))}"></div><b>${esc(name(p))} · Lv. ${p.level} · ${p.currentHp}/${hp(p)} PS ${esc(p.status||'')}</b><progress max="${hp(p)}" value="${p.currentHp}"></progress>${st.pendingSwitch?'<p>Pokémon esausto: scegli chi entra.</p>':`<div class="moves">${keys.map(k=>`<button data-action="move" data-move="${k}" ${k!=='STRUGGLE'&&!p.pp[k]?'disabled':''}>${esc(moves[k]?.name||'Scontro')}<small>${k==='STRUGGLE'?'Nessun PP disponibile':p.pp[k]+'/'+moves[k].pp+' PP'}</small></button>`).join('')}</div>`}<details ${st.pendingSwitch?'open':''}><summary>Cambia Pokémon</summary><div class="actions">${st.party.map((m,i)=>`<button data-action="switch" data-index="${i}" ${i===st.activeIndex||m.currentHp<=0?'disabled':''}>${esc(name(m))} · Lv. ${m.level}<small>${m.currentHp}/${hp(m)} PS</small></button>`).join('')}</div></details><button data-action="flee">Abbandona · conta come sconfitta</button><p>Inattività massima: 10 minuti dall’ultima azione accettata.</p>`;
 }
 async function actionBattle(action,value){await perform({type:'act',battleId:battle.id,revision:battle.revision,action,value});}
 function adminRender(){
  const r=state.stations.find(s=>s.position===editPosition).rules;
  root.querySelector('[data-admin]').innerHTML=`<p>Le regole valgono per test e modalità reale. Depositi e squadre già impegnati restano invariati.</p><div class="toolbar"><button data-action="toggle">${state.config.opened?'Chiudi nuove sfide':'Apri nuove sfide'}</button><a href="#route01-test">Collaudo con fondi di prova</a><button data-action="reset-all">Reset intera Route ${test?'TEST':'REALE'}</button></div><label>Postazione<select data-edit-position>${state.stations.map(s=>`<option ${s.position===editPosition?'selected':''} value="${s.position}">${s.position} · ${esc(s.owner_name||s.rules.bot_name)} · Deposito ${s.deposit} · ${s.battle_id?'In lotta':'Libera'}</option>`).join('')}</select></label><form data-rule class="rule"><h2>Bot e posta del posto ${r.position}</h2><div class="fields"><label>Nome bot<input name="bot_name" maxlength="60" value="${esc(r.bot_name)}" required></label><label>Sprite<select name="bot_sprite">${Object.entries(sprites.sprites).map(([k,v])=>`<option value="${k}" ${k===r.bot_sprite?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label><label>Posta PD<input name="stake" type="number" min="1" max="100000000" value="${r.stake}" required></label><label>Premio bot PD<input name="reward" type="number" min="0" max="100000000" value="${r.reward}" required></label><label>Vittorie premiate / giorno<input name="daily_limit" type="number" min="1" max="100" value="${r.daily_limit}" required></label></div>${Array.from({length:6},(_,i)=>{const p=r.bot_team[i];return `<fieldset><legend>Pokémon ${i+1}</legend><div class="fields"><label>Specie<select name="species-${i}"><option value="">Nessuno</option>${Object.values(db).filter(p=>p.id<=251).map(q=>`<option value="${q.id}" ${p?.speciesId===q.id?'selected':''}>${esc(q.name)}</option>`).join('')}</select></label><label>Livello<input name="level-${i}" type="number" min="1" max="100" value="${p?.level||5}"></label></div><label>Mosse (massimo 4; nessuna selezione = mosse del livello)<select name="moves-${i}" multiple size="4">${Object.entries(moves).map(([k,m])=>`<option value="${k}" ${p?.moves?.includes(k)?'selected':''}>${esc(m.name)}</option>`).join('')}</select></label></fieldset>`;}).join('')}<button class="primary">Salva regole</button><button type="button" data-action="reset-one">Reset posto ${r.position}</button></form><section class="rule"><h2>Coordinate e collisioni</h2><p>Rosso = bloccato. Tocca per modificare la griglia, oppure spostare un punto. Coordinate riferite alla mappa originale 400 × 672.</p><select data-map-tool><option value="block">Blocca casella</option><option value="clear">Rendi percorribile</option><option value="entry">Sposta ingresso</option>${[1,2,3,4,5].map(n=>`<option value="${n}">Sposta allenatore ${n}</option>`).join('')}</select><canvas width="400" height="672" class="map-editor"></canvas><button data-action="save-map">Salva mappa</button></section>`;
  draftMap=structuredClone(state.config.map);const canvas=root.querySelector('.map-editor'),img=new Image();img.onload=()=>drawEditor(img);img.src=new URL('../../Route/map.png',import.meta.url);
  const paint=e=>{e.preventDefault();const r=canvas.getBoundingClientRect(),x=Math.floor((e.clientX-r.left)/r.width*400/16),y=Math.floor((e.clientY-r.top)/r.height*672/16);if(x<0||x>=25||y<0||y>=42)return;const idx=y*25+x,tool=root.querySelector('[data-map-tool]').value,set=new Set(draftMap.blocked);if(tool==='block')set.add(idx);else if(tool==='clear')set.delete(idx);else{const point={x:x*16+8,y:y*16+8};if(tool==='entry')draftMap.entry=point;else draftMap.stations[Number(tool)-1]=point;}draftMap.blocked=[...set];drawEditor(img);};
  let painting=false;canvas.onpointerdown=e=>{if(busy)return;painting=true;canvas.setPointerCapture(e.pointerId);paint(e);};canvas.onpointermove=e=>{if(painting)paint(e);};canvas.onpointerup=canvas.onpointercancel=()=>painting=false;
 }
 function drawEditor(img){const ctx=root.querySelector('.map-editor')?.getContext('2d');if(!ctx)return;ctx.imageSmoothingEnabled=false;ctx.drawImage(img,0,0);ctx.fillStyle='#e3263666';for(const idx of draftMap.blocked)ctx.fillRect(idx%25*16,Math.floor(idx/25)*16,16,16);ctx.fillStyle='#00f0ff';ctx.font='bold 14px monospace';draftMap.stations.forEach((p,i)=>ctx.fillText(String(i+1),p.x-4,p.y));ctx.fillText('E',draftMap.entry.x-4,draftMap.entry.y);}
 root.addEventListener('change',e=>{if(e.target.matches('[data-edit-position]')){editPosition=Number(e.target.value);adminRender();}});
 root.addEventListener('submit',async e=>{if(!e.target.matches('[data-rule]'))return;e.preventDefault();if(busy||pending)return;const f=new FormData(e.target),bot_team=[];for(let i=0;i<6;i++){if(!f.get('species-'+i))continue;const m=f.getAll('moves-'+i);if(m.length>4){message='Scegli al massimo quattro mosse per Pokémon.';render();return;}bot_team.push({speciesId:Number(f.get('species-'+i)),level:Number(f.get('level-'+i)),...(m.length?{moves:m}:{})});}const r=state.stations.find(s=>s.position===editPosition).rules;await perform({type:'admin',action:'rule',args:{position:editPosition,revision:r.revision,bot_name:f.get('bot_name'),bot_sprite:f.get('bot_sprite'),stake:Number(f.get('stake')),reward:Number(f.get('reward')),daily_limit:Number(f.get('daily_limit')),bot_team}});if(!pending)adminRender();});
 root.addEventListener('click',async e=>{
  const b=e.target.closest('button');if(!b||b.disabled||busy)return;if(b.hasAttribute('data-interact')){mapView?.interact();return;}const a=b.dataset.action;if(!a)return;if(pending&&a!=='retry')return;
  if(a==='close'){dialog.close();battle=null;return;}if(a==='station'){openStation(Number(b.dataset.position));return;}if(a==='resume'){battle=state.active;openBattle();return;}
  if(a==='retry'){await perform(pending||{});return;}
  if(a==='refresh'){try{busy=true;render();await load();if(admin)adminRender();}catch(e){message=e.message;}finally{busy=false;render();}return;}
  if(a==='sprite'){await command('sprite',{sprite:b.dataset.sprite});return;}
  if(a==='challenge'){if(!confirm('Iniziare questa sfida con le condizioni mostrate? La posta, se prevista, sarà bloccata fino alla conclusione.'))return;await perform({type:'start',position:selected});return;}
  if(a==='init'){await perform({type:'init',battleId:battle.id,revision:battle.revision});return;}
  if(a==='move'||a==='switch'){await actionBattle(a,a==='move'?b.dataset.move:Number(b.dataset.index));return;}
  if(a==='flee'){if(confirm('Abbandonare? La posta sarà persa.'))await actionBattle('flee');return;}
  if(['occupy','proceed','pass','update','withdraw','restart'].includes(a)){
   if(['occupy','update','withdraw'].includes(a)&&!confirm(a==='occupy'?'Depositare la posta e lasciare qui una copia della tua squadra? Un eventuale vecchio posto sarà liberato.':a==='update'?'Sostituire la copia difensiva con la squadra attuale?':'Ritirarti e recuperare il deposito?'))return;
   await command(a,{position:selected});return;
  }
  if(a==='toggle'){await perform({type:'admin',action:'open',args:{opened:!state.config.opened}});adminRender();}
  if(a==='save-map'){await perform({type:'admin',action:'map',args:{map:draftMap,revision:state.config.revision}});if(!pending)adminRender();}
  if(a==='reset-all'||a==='reset-one'){if(confirm('Reset '+(a==='reset-all'?'dell’intera Route':'del posto '+editPosition)+': i proprietari perderanno il posto e recupereranno i depositi non impegnati. Le difese attive finiranno prima del reset. Lo storico rimane. Confermi?')){await perform({type:'admin',action:'reset',args:a==='reset-one'?{position:editPosition}:{}});adminRender();}}
  if(a==='technical'&&confirm('Annullare per errore tecnico? Restituisce la posta allo sfidante; il difensore conserva il deposito. Nessun premio o conquista.'))await perform({type:'admin',action:'cancel',args:{battle:b.dataset.battle}});
 });
 try{await load();if(!current())return;render();if(admin)adminRender();}catch(e){message=e.message;root.querySelector('.status').textContent=message;root.querySelector('[data-toolbar]').innerHTML='<button data-action="refresh">Riprova caricamento</button>';}
 const poll=setInterval(async()=>{if(!current()){cleanup();return;}if(!busy&&!dialog.open&&!admin){try{await load();render();}catch{}}},15000);
 function cleanup(){if(destroyed)return;destroyed=true;clearInterval(poll);mapView?.destroy();dialog.close();}
 const observer=new MutationObserver(()=>{if(!current()){cleanup();observer.disconnect();}});observer.observe(document.body,{childList:true,subtree:true});
 return cleanup;
}
