const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const errors={NOT_AUTHORIZED:'Accedi con la tua scheda allenatore.',ADMIN_REQUIRED:'Questa operazione è riservata agli amministratori.',OFFER_CHANGED:'L’offerta è cambiata. Controlla i nuovi dati e conferma nuovamente.',TEAM_CHANGED:'La squadra è cambiata. Controllala e conferma nuovamente.',OFFER_UNAVAILABLE:'Offerta nascosta, archiviata o fuori dal periodo di vendita.',SOLD_OUT:'Offerta esaurita.',INSUFFICIENT_BALANCE:'Pokédollari insufficienti.',STARTER_REQUIRED:'Scegli prima il tuo starter nella pagina La mia squadra.',STARTER_PROTECTED:'Lo starter non può essere liberato.',NOT_OWNED:'Il Pokémon selezionato non appartiene alla tua squadra.',RELEASE_REQUIRED:'Scegli quale Pokémon liberare: la squadra è completa.',TEAM_PENDING:'Completa prima l’acquisizione in sospeso in La mia squadra.',BATTLE_ACTIVE:'Concludi prima la battaglia in corso.',OPERATION_MISMATCH:'Il tentativo salvato non corrisponde a questo acquisto.'};
export async function mountRocketShop(host,{client,userId,admin=false,isCurrent=()=>true,onBalance=()=>{}}){
 const root=host.attachShadow({mode:'open'}),key='champion:rocket-purchase:'+userId;
 let state=null,busy=false,message='',choice=null,draft=null,pending=null,offset=0;
 try{pending=JSON.parse(localStorage.getItem(key));}catch{}
 const current=()=>host.isConnected&&isCurrent();
 const pokemon=id=>state?.catalog.find(p=>p.id===Number(id));
 const name=id=>pokemon(id)?.name||window.ROUTE_POKEMON_DB?.[id]?.name||String(id);
 const date=value=>value?new Date(value).toLocaleString('it-IT'):'—';
 const localDate=value=>{if(!value)return '';const d=new Date(value);return new Date(d-d.getTimezoneOffset()*60000).toISOString().slice(0,16);};
 async function rpc(fn,args){const {data,error}=await client.rpc(fn,args);if(error){const code=Object.keys(errors).find(c=>error.message?.includes(c));const e=Error(errors[code]||(['PGRST202','42883','42P01'].includes(error.code)?'Installa la migrazione Negozio Team Rocket su Supabase.':error.code?.startsWith('23')||error.code?.startsWith('22')?'Dati non validi: prezzo minimo 500 PD, livello 1–100, quantità intera e date coerenti.':'Operazione non confermata. Riprova con lo stesso tentativo.'));e.definitive=!!code||['PGRST202','42883','42P01'].includes(error.code)||error.code?.startsWith('23')||error.code?.startsWith('22');throw e;}return data;}
 async function load(){state=await rpc('get_rocket_shop',{p_admin:admin,p_offset:offset});try{const funds=await client.rpc('get_route01_funds');if(!funds.error&&funds.data){state.balance=funds.data.available;state.locked=funds.data.locked;}}catch{}if(current())onBalance(state.balance);}
 function render(){
  if(!current())return;
  root.innerHTML=`<link rel="stylesheet" href="${new URL('./style.css?v=1',import.meta.url)}"><main><a href="${admin?'#admin':'#dashboard'}">← ${admin?'Amministrazione':'Home'}</a><header><span class="rocket">R</span><div><span class="eyebrow">TEAM ROCKET</span><h1>${admin?'Negozio Team Rocket':'Il mercato dei Pokémon'}</h1></div></header><p>${admin?'Gestisci offerte e consulta gli acquisti.':'I Pokémon acquistati entrano nella tua squadra. Massimo sei compagni, senza Box.'}</p><p role="status" class="message">${esc(message)} ${busy?'Attendi…':''}</p>${pending?`<aside>Un acquisto attende conferma dal server. Riprova per verificarlo senza pagare due volte.<button data-action="retry" ${busy?'disabled':''}>Verifica acquisto</button></aside>`:''}${state?`<div class="toolbar"><strong>Saldo disponibile: ${state.balance} PD</strong><span>Bloccati nella Route: ${state.locked||0} PD</span><a href="#my-team">La mia squadra · ${state.team.length}/6</a><button data-action="reload" ${busy?'disabled':''}>Aggiorna</button>${admin?'<button data-action="new">Crea offerta</button><a href="#rocket-list">Vedi negozio</a>':''}</div>${draft?editor():''}${choice?confirmation():''}<div class="offers">${state.offers.length?state.offers.map(o=>`<article><img src="${esc(window.ROUTE_POKEMON_DB?.[o.species_id]?.sprites.front||pokemon(o.species_id)?.sprite)}" alt="${esc(name(o.species_id))}" width="112" height="112"><h2>${esc(name(o.species_id))}</h2><p>Livello ${o.level}</p><p>${esc(o.description)}</p><strong>${o.price} PD</strong><p>${o.stock===null?'Disponibilità illimitata':o.stock+' disponibili'}</p>${admin?`<p>${o.archived?'Archiviata':o.active?'Attiva':'Nascosta'} · ${date(o.starts_at)} → ${date(o.ends_at)}</p><button data-action="edit" data-id="${o.id}">Modifica</button><button data-action="hide" data-id="${o.id}">${o.active?'Nascondi':'Attiva'}</button><button data-action="archive" data-id="${o.id}">${o.archived?'Ripristina':'Archivia'}</button>`:`<button class="primary" data-action="buy" data-id="${o.id}" ${busy||pending||state.balance<o.price?'disabled':''}>Acquista</button>${state.balance<o.price?'<small>Saldo insufficiente</small>':''}`}</article>`).join(''):'<p>Nessuna offerta disponibile al momento.</p>'}</div><h2>Storico acquisti${admin?' di tutti gli allenatori':''}</h2><div class="history">${state.history.map(h=>`<article><strong>${esc(h.pokemon_name)} · Lv. ${h.level}</strong><span>${h.price} PD · ${date(h.created_at)}</span>${admin?`<span>${esc(h.trainer_name)} · ${esc(h.trainer_code)}</span>`:''}</article>`).join('')||'<p>Nessun acquisto.</p>'}</div><div class="toolbar"><button data-action="previous" ${offset===0?'disabled':''}>Precedenti</button><button data-action="next" ${state.history.length<50?'disabled':''}>Successivi</button></div>`:'<button data-action="reload">Carica negozio</button>'}</main>`;
  if(busy)root.querySelectorAll('button,input,select,textarea').forEach(e=>e.disabled=true);
 }
 function editor(){const d=draft;return `<form data-editor><h2>${d.revision?'Modifica offerta':'Nuova offerta'}</h2><div class="fields"><label>Pokémon<select name="species_id" required>${state.catalog.map(p=>`<option value="${p.id}" ${p.id===Number(d.species_id)?'selected':''}>${esc(p.name)}</option>`).join('')}</select></label><label>Livello<input name="level" type="number" min="1" max="100" step="1" value="${d.level}" required></label><label>Prezzo (minimo 500 PD)<input name="price" type="number" min="500" max="9007199254740991" step="1" value="${d.price??''}" required></label><label>Quantità restante (vuoto = illimitata)<input name="stock" type="number" min="0" max="2147483647" step="1" value="${d.stock??''}"></label><label>Stato<select name="active"><option value="false" ${!d.active?'selected':''}>Nascosta</option><option value="true" ${d.active?'selected':''}>Attiva</option></select></label><label>Ordine<input name="display_order" type="number" step="1" value="${d.display_order}" required></label><label>Inizio (ora locale)<input name="starts_at" type="datetime-local" value="${localDate(d.starts_at)}"></label><label>Fine (ora locale)<input name="ends_at" type="datetime-local" value="${localDate(d.ends_at)}"></label><label>Descrizione<textarea name="description" maxlength="240">${esc(d.description)}</textarea></label></div><button class="primary" type="submit">Salva offerta</button><button type="button" data-action="cancel-edit">Annulla</button></form>`;}
 function confirmation(){const o=choice.offer,full=state.team.length===6;return `<section class="confirmation" aria-label="Conferma acquisto"><h2>Conferma acquisto</h2><p><b>${esc(name(o.species_id))} · Livello ${o.level}</b> · ${o.price} PD</p>${full?`<label>Squadra completa: scegli chi liberare<select data-release><option value="">Seleziona un Pokémon</option>${state.team.map(p=>`<option value="${esc(p.uid)}" ${p.isStarter?'disabled':''} ${choice.release===p.uid?'selected':''}>${esc(name(p.speciesId))} · Lv. ${p.level}${p.isStarter?' · Starter protetto':''}</option>`).join('')}</select></label><p data-release-summary>${choice.release?'Libererai definitivamente '+esc(name(state.team.find(p=>p.uid===choice.release)?.speciesId))+' · Lv. '+state.team.find(p=>p.uid===choice.release)?.level:'Nessun Pokémon verrà liberato finché non confermi.'}</p>`:'<p>Il Pokémon occuperà un posto libero nella squadra.</p>'}<button data-action="confirm" class="primary" ${busy||pending||(full&&!choice.release)?'disabled':''}>Conferma · ${o.price} PD</button><button data-action="cancel">Annulla</button></section>`;}
 async function purchase(){
  const result=await rpc('buy_rocket_pokemon',pending);
  pending=null;localStorage.removeItem(key);choice=null;
  message=`Acquisto riuscito: ${result.purchase.pokemon_name} · Lv. ${result.purchase.level} è nella tua squadra. Pagati ${result.purchase.price} PD.`;
  window.dispatchEvent(new CustomEvent('route-team-updated'));
  try{await load();}catch{message+=' Premi Aggiorna per rileggere saldo e disponibilità.';}
 }
 root.addEventListener('change',e=>{if(e.target.matches('[data-release]')){choice.release=e.target.value;render();}});
 root.addEventListener('submit',async e=>{
  if(!e.target.matches('[data-editor]'))return;e.preventDefault();if(busy||!current())return;
  const v=Object.fromEntries(new FormData(e.target));draft={...draft,...v,level:Number(v.level),species_id:Number(v.species_id),price:Number(v.price),stock:v.stock===''?null:Number(v.stock),display_order:Number(v.display_order),active:v.active==='true',starts_at:v.starts_at?new Date(v.starts_at).toISOString():null,ends_at:v.ends_at?new Date(v.ends_at).toISOString():null};
  busy=true;message='';render();try{await rpc('admin_save_rocket_offer',{p_id:draft.id,p_revision:draft.revision,p_offer:draft});draft=null;await load();message='Offerta salvata.';}catch(e){message=e.message;}finally{busy=false;render();}
 });
 root.addEventListener('click',async e=>{
  const b=e.target.closest('button[data-action]');if(!b||b.disabled||busy||!current())return;const action=b.dataset.action;
  if(action==='cancel'){choice=null;render();return;}
  if(action==='cancel-edit'){draft=null;render();return;}
  if(action==='new'){draft={id:crypto.randomUUID(),revision:0,species_id:state.catalog[0]?.id,level:5,price:null,stock:null,active:false,archived:false,display_order:0,description:''};render();return;}
  if(action==='edit'){draft={...state.offers.find(o=>o.id===b.dataset.id)};render();return;}
  busy=true;message='';render();
  try{
   if(action==='reload')await load();
   if(action==='previous'||action==='next'){offset=Math.max(0,offset+(action==='next'?50:-50));await load();}
   if(action==='buy'){await load();const offer=state.offers.find(o=>o.id===b.dataset.id);if(!offer)throw Error(errors.OFFER_UNAVAILABLE);if(!state.team.length)throw Error(errors.STARTER_REQUIRED);if(state.pending)throw Error(errors.TEAM_PENDING);choice={offer:{...offer},teamRevision:state.teamRevision,release:null};}
   if(action==='confirm'){
    if(pending||!choice)return;
    const attempt={p_offer:choice.offer.id,p_revision:choice.offer.revision,p_team_revision:choice.teamRevision,p_operation:crypto.randomUUID(),p_release:choice.release||null};
    localStorage.setItem(key,JSON.stringify(attempt));pending=attempt;await purchase();
   }
   if(action==='retry')await purchase();
   if(action==='hide'||action==='archive'){const offer={...state.offers.find(o=>o.id===b.dataset.id)};if(action==='hide')offer.active=!offer.active;else offer.archived=!offer.archived;await rpc('admin_save_rocket_offer',{p_id:offer.id,p_revision:offer.revision,p_offer:offer});await load();message='Offerta aggiornata.';}
  }catch(e){message=e.message;if(e.definitive){if(action==='confirm'||action==='retry'){pending=null;localStorage.removeItem(key);choice=null;}try{await load();}catch{}}}finally{busy=false;render();}
 });
 root.addEventListener('error',e=>{if(e.target.tagName==='IMG'){e.target.removeAttribute('src');e.target.alt='Sprite non disponibile';}},true);
 busy=true;render();try{await load();}catch(e){message=e.message;}finally{busy=false;render();}
}
