import {getPokemonById,getMoveById,typeNames,evolutionChain,evolutionMethod} from '../pokedex/data.mjs';
import {calculateStats,calculateExpForLevel} from '../team/model.mjs';
import {LEGACY_MOVE_KEYS,ROUTE_MOVE_SHOP} from './route-shop.mjs';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(action,label,disabled,extra='')=>`<button data-action="${action}" ${disabled?'disabled':''} ${extra}>${esc(label)}</button>`;
export function routeStarterView(p){
 const species=getPokemonById(p.speciesId),stats=calculateStats(p.speciesId,p.level),next=p.level<100?calculateExpForLevel(p.speciesId,p.level+1):null;
 return `<article class="hero"><img src="${esc(species.sprites.front)}" alt="${esc(species.name)}" width="112" height="112"><h2>${esc(species.name)} <small>Lv. ${p.level}</small></h2><p>${species.types.map(t=>typeNames[t]).join(' / ')}</p><p>PS ${p.currentHp} / ${stats.hp}</p><p>${p.exp} XP totali${next===null?' · Livello massimo':' · Prossimo livello: '+next+' XP'}</p><div class="stats">${Object.entries({hp:'PS',attack:'Attacco',defense:'Difesa',spAttack:'Att. speciale',spDefense:'Dif. speciale',speed:'Velocità'}).map(([key,label])=>`<div><small>${label}</small><strong>${stats[key]}</strong></div>`).join('')}</div></article><article><h2>Mosse equipaggiate</h2>${p.moves.map(key=>{const m=getMoveById(key);return `<p><strong>${esc(m?.name||key)}</strong>${m?`<br><small>${typeNames[m.type]} · Potenza ${m.power||'—'} · PP ${m.pp}</small>`:''}</p>`;}).join('')}</article><article><h2>Linea evolutiva Crystal</h2>${evolutionChain(p.speciesId).map(e=>`<p>${esc(e.from.name)} → ${esc(e.pokemon.name)} · ${esc(evolutionMethod(e))}</p>`).join('')||'<p>Nessuna evoluzione.</p>'}<p>Le evoluzioni per livello avvengono durante la progressione della squadra.</p></article>`;
}
export function routeShopView(p,legacy,{balance,active,selectedMove}){
 const known=[...new Set([...(p.knownMoves||[]),...p.moves,...(legacy.knownMoves||[]).map(k=>LEGACY_MOVE_KEYS[k])])].filter(k=>getMoveById(k));
 return `<p>Le mosse acquistate restano apprese. Puoi equipaggiare fino a quattro mosse.</p>${active?'<p>Concludi la lotta prima di modificare le mosse.</p>':''}<article><h2>Mosse apprese</h2>${known.map(key=>button('selectMove',getMoveById(key).name,active||p.moves.includes(key),`data-move="${key}"`)).join('')}${selectedMove&&known.includes(selectedMove)?`<h3>Equipaggia ${esc(getMoveById(selectedMove).name)}</h3>${Array.from({length:Math.min(4,p.moves.length+1)},(_,i)=>button('equip',`Slot ${i+1}: ${getMoveById(p.moves[i])?.name||'Libero'}`,active,`data-slot="${i}"`)).join('')}`:''}</article>${ROUTE_MOVE_SHOP.filter(o=>o.starters.includes(legacy.origin)).map(o=>`<article><h3>${esc(getMoveById(o.key).name)}</h3><p>Livello ${o.level} · ${o.price} ₽</p>${button('buy',known.includes(o.key)?'Appresa':'Acquista',active||known.includes(o.key)||p.level<o.level||balance<o.price,`data-move="${o.key}"`)}</article>`).join('')}`;
}
