import {getPokemonById,getPokemonEvolution,listPokemon} from '../pokedex/data.mjs';
export const evolutionMessages={STALE_TEAM:'La squadra è cambiata. Aggiorna e prepara di nuovo l’operazione.',STALE_INVENTORY:'Lo Zaino è cambiato. Aggiorna e riprova.',ITEM_NOT_OWNED:'Non possiedi l’oggetto richiesto.',EVOLUTION_NOT_ALLOWED:'Questo oggetto non può essere usato su questo Pokémon. Gli strumenti da scambio richiedono uno scambio.',INSUFFICIENT_BALANCE:'Saldo disponibile insufficiente.',BATTLE_ACTIVE:'Concludi prima gli incontri in corso.',MEMBER_NOT_FOUND:'Il Pokémon non è più nella squadra.',STARTER_PROTECTED:'Lo starter resta con te e non può essere scambiato.',STARTER_REQUIRED:'Scegli prima lo starter.',PENDING_EXISTS:'Completa prima l’acquisizione in attesa.',NOT_AUTHORIZED:'Accedi con una scheda allenatore attiva.',TRAINER_NOT_FOUND:'Codice allenatore non valido, account non attivo o uguale al tuo.',TRADE_NOT_FOUND:'Scambio non disponibile.',TRADE_CLOSED:'Questo scambio è già stato concluso o annullato.',TRADE_EXPIRED:'La proposta di scambio è scaduta.',TRADE_REQUIREMENTS:'Scegli la specie e il livello richiesti nella proposta.',TRADE_LIMIT:'Hai già dieci proposte aperte. Annullane una prima di continuare.',OPERATION_MISMATCH:'Il tentativo non corrisponde all’operazione salvata.',INVALID_COMMAND:'Operazione non valida.',INVALID_ITEM:'Oggetto evolutivo non valido.',INVALID_POKEMON:'Pokémon o livello richiesto non valido.',INVALID_SPECIES:'Evoluzione non disponibile.'};
export function createEvolutionAPI(client,userId,{storage=globalThis.localStorage}={}){
 const key='champion:evolutions:'+userId;
 const pending=()=>{try{return JSON.parse(storage.getItem(key)||'null');}catch{throw Error('Impossibile leggere l’operazione salvata.');}};
 async function rpc(name,args={}){
  const response=await client.rpc(name,args);
  if(response.error){const code=Object.keys(evolutionMessages).find(k=>response.error.message?.includes(k));const e=Error(code?evolutionMessages[code]:response.error.code==='PGRST202'?'Evoluzioni e scambi devono essere attivati su Supabase.':'Salvataggio non confermato. Premi Riprova operazione.');e.definite=!!code;e.unavailable=response.error.code==='PGRST202';throw e;}
  return response.data;
 }
 async function send(operation){try{const data=await rpc(operation.name,operation.args);storage.removeItem(key);return data;}catch(e){if(e.definite)storage.removeItem(key);throw e;}}
 async function command(name,args){if(pending())throw Error('Un’operazione è in attesa. Premi Riprova operazione prima di continuare.');const operation={name,args:{...args,p_operation:crypto.randomUUID()}};storage.setItem(key,JSON.stringify(operation));return send(operation);}
 return {
  pending,
  async read(){const results=await Promise.allSettled([rpc('get_route_evolutions'),rpc('get_route_trades')]);const evolution=results[0].status==='fulfilled'?results[0].value:null;return {evolutions:Array.isArray(evolution?.items)&&Array.isArray(evolution?.options)?evolution:null,trades:results[1].status==='fulfilled'&&Array.isArray(results[1].value)?results[1].value:[],warning:results.filter(r=>r.status==='rejected').map(r=>r.reason.message).join(' ')};},
  evolve:(option,state)=>command('route_evolution_command',{p_action:'evolve',p_item:option.item,p_uid:option.uid,p_team_revision:state.teamRevision,p_inventory_revision:state.inventoryRevision}),
  buy:(item,state)=>command('route_evolution_command',{p_action:'buy',p_item:item,p_team_revision:state.teamRevision,p_inventory_revision:state.inventoryRevision}),
  trade:args=>command('route_trade_command',args),
  retry:()=>{const operation=pending();if(!operation)throw Error('Nessuna operazione da riprovare.');return send(operation);}
 };
}
export const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const itemName=(item,state)=>state?.items.find(i=>i.id===item)?.name||({metal_coat:'Metalcoperta',kings_rock:'Roccia di Re',dragon_scale:'Squama Drago',up_grade:'Upgrade'}[item])||item;
export function tradeResult(p,item=null){const e=getPokemonEvolution(p.speciesId).find(e=>e.method==='trade'&&(e.heldItem||null)===(item||null));return getPokemonById(e?.to||p.speciesId)?.name||'Pokémon';}
export function evolutionControls(p,state,busy){
 if(!state)return '';
 const options=state.options.filter(o=>o.uid===p.uid);
 return `<section class="evolution-controls">${options.map(o=>o.method==='item'?`<p>${esc(o.itemName)}: ${o.quantity} nello Zaino</p><button data-action="evolve-item" data-uid="${esc(p.uid)}" data-item="${esc(o.item)}" ${busy||o.quantity<1?'disabled':''}>Evolvi in ${esc(o.name)}</button>`:`<p>${esc(o.itemName)} + scambio → ${esc(o.name)} · ${o.quantity} nello Zaino</p>`).join('')}${!p.isStarter?`<button data-action="trade-offer" data-uid="${esc(p.uid)}" ${busy?'disabled':''}>Proponi scambio</button>`:''}</section>`;
}
export function evolutionShop(state,busy){return state?`<details class="evolution-shop"><summary>Pietre e strumenti evolutivi</summary><p>Le pietre si usano sulla squadra. Gli altri strumenti si consumano durante uno scambio accettato da entrambi gli allenatori. Le pietre trovate nel Laboratorio Fossili sono già utilizzabili.</p><p>Saldo disponibile: ${state.balance} PD</p><div class="evolution-items">${state.items.map(i=>`<article><strong>${esc(i.name)}</strong><p>Nello Zaino: ${i.quantity}</p><button data-action="buy-evolution" data-item="${esc(i.id)}" ${busy||state.balance<i.price?'disabled':''}>Compra 1 · ${i.price} PD</button></article>`).join('')}</div></details>`:'';}
export function tradeList(trades,busy){return `<section class="trades"><h2>Scambi tra allenatori</h2><p>Proponi uno scambio dalla scheda di un Pokémon. Lo starter resta sempre con te. Ogni proposta dura 24 ore; il destinatario deve accettarla. Lo scambio trasferisce davvero i due Pokémon.</p>${trades.length?trades.map(t=>`<article><strong>${esc(t.outgoing?'A':'Da')} ${esc(t.name)} · ${esc(t.code)}</strong><p>Offerta: ${esc(getPokemonById(t.pokemon.speciesId)?.name)} Lv. ${t.pokemon.level}${t.item?' con '+esc(itemName(t.item,null)):''}${tradeResult(t.pokemon,t.item)!==getPokemonById(t.pokemon.speciesId)?.name?' → '+esc(tradeResult(t.pokemon,t.item)):''}</p><p>Richiesta: ${esc(getPokemonById(t.requestedSpecies)?.name)} · almeno Lv. ${t.minLevel}</p>${t.status==='pending'&&!t.expired?`<p>Scade: ${new Date(t.expiresAt).toLocaleString('it-IT')}</p>${!t.outgoing?`<button data-action="trade-accept" data-trade="${t.id}" ${busy?'disabled':''}>Scegli Pokémon e accetta</button>`:''}<button data-action="${t.outgoing?'trade-cancel':'trade-decline'}" data-trade="${t.id}" ${busy?'disabled':''}>${t.outgoing?'Annulla proposta':'Rifiuta'}</button>`:`<p>${{accepted:'Scambio completato',cancelled:'Proposta annullata',declined:'Proposta rifiutata',pending:'Proposta scaduta'}[t.status]||''}</p>`}</article>`).join(''):'<p>Nessuna proposta di scambio.</p>'}</section>`;}
export const speciesChoices=()=>listPokemon().map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');
export function heldItemChoices(p,state){return `<option value="">Nessun oggetto</option>`+(state?.options||[]).filter(o=>o.uid===p.uid&&o.method==='trade'&&o.quantity>0).map(o=>`<option value="${esc(o.item)}">${esc(o.itemName)} → ${esc(o.name)}</option>`).join('');}
