import {createTeamAPI} from './api.mjs?v=gifts-1';
import {calculateStats,calculateExpForLevel,TEAM_LIMIT} from './model.mjs';
import {getPokemonById,getMoveById,typeNames,evolutionChain,evolutionMethod} from '../pokedex/data.mjs';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statuses={poison:'Avvelenato',burn:'Scottato',paralysis:'Paralizzato',sleep:'Addormentato',freeze:'Congelato',PSN:'Avvelenato',BRN:'Scottato',PAR:'Paralizzato',SLP:'Addormentato',FRZ:'Congelato'};
export async function mountTeam(host,{client,isCurrent=()=>true,onBalance=()=>{},token=null,api=createTeamAPI(client)}={}){
 const root=host.attachShadow({mode:'open'});let state=null,busy=false,message='',error=false,pendingHidden=false,pendingBattle=null;
 root.innerHTML=`<link rel="stylesheet" href="${new URL('./style.css?v=team-exp-2',import.meta.url)}"><main><a href="#dashboard">← Home</a><div class="eyebrow">I TUOI COMPAGNI DI AVVENTURE</div><h1>La mia squadra</h1><p>Massimo 6 Pokémon, starter compreso. Puoi cambiare l’ordine; lo starter resta sempre con te.</p><p data-message role="status"></p><div data-content></div><dialog aria-labelledby="release-title"><div data-confirmation></div></dialog></main>`;
 const content=root.querySelector('[data-content]'),dialog=root.querySelector('dialog');
 const current=()=>host.isConnected&&isCurrent();
 function expBar(p){const base=calculateExpForLevel(p.speciesId,p.level),next=calculateExpForLevel(p.speciesId,p.level+1),max=p.level>=100?1:Math.max(1,next-base),value=p.level>=100?1:Math.min(max,Math.max(0,p.exp-base));return '<label class="xp">EXP '+(p.level>=100?'· Livello massimo':value+' / '+max+' · '+(max-value)+' al prossimo livello')+'<progress class="exp-bar" aria-label="Esperienza di '+esc(getPokemonById(p.speciesId).name)+'" value="'+value+'" max="'+max+'"></progress></label>';}
 function card(p,index,replace=false){
 const species=getPokemonById(p.speciesId),stats=calculateStats(p.speciesId,p.level),isStarter=p.isStarter;
 return `<article class="member ${isStarter?'starter':''}" data-uid="${esc(p.uid)}"><span class="tag">${replace?'':`Slot ${index+1} · `}${isStarter?'STARTER':'SQUADRA'}</span><div class="portrait"><img src="${esc(species.sprites.front)}" alt="${esc(species.name)}" loading="${isStarter?'eager':'lazy'}"></div><h2>${esc(species.name)} <small>Lv. ${p.level}</small></h2><p>${species.types.map(t=>typeNames[t]).join(' / ')}</p><label>PS ${p.currentHp} / ${stats.hp}<progress max="${stats.hp}" value="${p.currentHp}"></progress></label><p class="status">${p.currentHp===0?'Esausto':p.status?esc(statuses[p.status]||p.status):'In salute'}</p>${!replace?`${expBar(p)}<details ${isStarter?'open':''}><summary>Statistiche, mosse ed evoluzioni</summary><div class="stats">${Object.entries({hp:'PS',attack:'Attacco',defense:'Difesa',spAttack:'Att. speciale',spDefense:'Dif. speciale',speed:'Velocità'}).map(([key,label])=>`<div><small>${label}</small><strong>${stats[key]}</strong></div>`).join('')}</div><ul>${p.moves.map(key=>{const m=getMoveById(key);return `<li>${esc(m?.name||key)}${m?` · ${typeNames[m.type]} · PP ${m.pp}`:''}</li>`;}).join('')}</ul><h3>Linea evolutiva Crystal</h3>${evolutionChain(p.speciesId).map(e=>`<p>${esc(e.from.name)} → ${esc(e.pokemon.name)} · ${esc(evolutionMethod(e))}</p>`).join('')||'<p>Nessuna evoluzione.</p>'}</details><div class="order"><button data-action="up" data-index="${index}" ${busy||index===0?'disabled':''} aria-label="Sposta ${esc(species.name)} prima">↑ Prima</button><button data-action="down" data-index="${index}" ${busy||index===state.team.length-1?'disabled':''} aria-label="Sposta ${esc(species.name)} dopo">↓ Dopo</button></div>`:''}<button class="${isStarter?'protected':'danger'}" data-action="${replace?'replace':'release'}" data-uid="${esc(p.uid)}" ${busy||isStarter?'disabled':''}>${isStarter?'STARTER · NON LIBERABILE':replace?'LIBERA E SOSTITUISCI':'LIBERA'}</button></article>`;
 }
 function render(){
 if(!current())return;
 root.querySelector('[data-message]').textContent=message+(state?.gifts?.some(g=>g.status==='queued')?' Hai regali in attesa: scegli lo starter, concludi la battaglia o completa prima l’acquisizione già aperta.':'');
 if(!state){content.innerHTML=`<p>${error?'La squadra non è disponibile.':'Caricamento della squadra…'}</p><button data-action="reload" ${busy?'disabled':''}>Riprova</button>`;return;}
 if(!state.team.length){content.innerHTML='<p>Scegli il tuo starter iniziale. Gli altri Pokémon potranno entrare tramite QR o regali.</p><div class="members">'+[1,4,7].map(id=>{const p=getPokemonById(id);return '<article class="member"><img width="112" height="112" src="'+esc(p.sprites.front)+'" alt="'+esc(p.name)+'"><h2>'+esc(p.name)+'</h2><button data-action="choose" data-species="'+p.slug+'" '+(busy?'disabled':'')+'>Scegli '+esc(p.name)+'</button></article>';}).join('')+'</div>';return;}
 content.innerHTML=`${pendingBattle?'<p>Hai un incontro salvato.</p><button data-action="battle">Riprendi l’incontro</button>':''}<div class="toolbar"><strong>${state.team.length} / ${TEAM_LIMIT} Pokémon</strong><button data-action="reload" ${busy?'disabled':''}>Aggiorna</button><button data-action="heal" ${busy?'disabled':''}>Cura la squadra · Gratis</button><a href="#scan">Scansiona QR Pokémon</a><a href="#gifts">Regali</a><a href="#starter-inventory">Fossili e scuola mosse</a></div>${state.pending?`<section class="pending"><h2>${state.team.length===6?'LA TUA SQUADRA È COMPLETA':'Un Pokémon ti aspetta'}</h2><p>Hai ottenuto <b>${esc(getPokemonById(state.pending.pokemon.speciesId).name)}</b>. ${state.team.length===6?'Per prenderlo devi liberare un membro della squadra.':'Puoi aggiungerlo al posto disponibile.'}</p>${pendingHidden?'<p>Acquisizione conservata in attesa. Nessun Pokémon è stato liberato.</p><button data-action="resume">Riprendi la scelta</button>':state.team.length===6?`<div class="members replacement">${state.team.map((p,i)=>card(p,i,true)).join('')}</div><button data-action="later">Annulla · decidi più tardi</button>`:'<button class="primary" data-action="accept">Aggiungi alla squadra</button>'}</section>`:''}<div class="members">${state.team.map((p,i)=>card(p,i)).join('')}${Array.from({length:6-state.team.length},(_,i)=>`<article class="empty"><span>Slot ${state.team.length+i+1}</span><b>Posto libero</b><p>Un Pokémon ricevuto tramite QR o regalo entrerà qui.</p></article>`).join('')}</div><p class="hint">Non c’è un Box: liberare un Pokémon lo rimuove definitivamente. Un Pokémon esausto resta nella squadra.</p>`;
 }
 async function load(){busy=true;error=false;render();try{state=await api.read();try{pendingBattle=await window.RouteEncounters?.pendingEncounter();}catch{pendingBattle=null;}if(token){if(state.team.length){state=await api.addPokemonToTeam(token);token=null;message=state.pending?'Scegli come completare l’acquisizione.':'Pokémon aggiunto alla squadra.';}else message='Scegli prima lo starter, poi riscatta questo QR.';}}catch(e){error=true;message=e.message;}finally{busy=false;render();}}
 async function perform(action){if(busy)return;busy=true;render();try{const next=await action();if(next===false)throw Error('Lo starter non può essere liberato.');state=await api.read();message='Squadra salvata.';error=false;}catch(e){message=e.message;try{state=await api.read();}catch{} }finally{busy=false;render();}}
 function confirmRelease(uid,replace){const p=state.team.find(p=>p.uid===uid);if(!p||p.isStarter)return;const name=getPokemonById(p.speciesId).name;const revision=state.revision;root.querySelector('[data-confirmation]').innerHTML=`<h2 id="release-title">Vuoi davvero liberare ${esc(name)}?</h2><p>${esc(name)} verrà rimosso definitivamente dalla tua squadra. Questa operazione non può essere annullata.</p>${replace?`<p>${esc(getPokemonById(state.pending.pokemon.speciesId).name)} occuperà lo stesso slot.</p>`:''}<div class="confirm-actions"><button data-cancel autofocus>ANNULLA</button><button class="danger" data-confirm>LIBERA ${esc(name.toUpperCase())}</button></div>`;dialog.showModal();root.querySelector('[data-cancel]').onclick=()=>dialog.close();root.querySelector('[data-confirm]').onclick=async()=>{if(busy)return;dialog.close();if(state.revision!==revision){message='La squadra è cambiata. Controllala prima di confermare.';render();return;}await perform(()=>replace?api.replaceTeamPokemon(uid):api.releasePokemon(uid));};}
 root.addEventListener('click',async event=>{const b=event.target.closest('button[data-action]');if(!b||b.disabled||busy)return;const a=b.dataset.action;if(a==='choose'){busy=true;render();try{const read=await client.functions.invoke('bright-processor',{body:{type:'read'}});if(read.error)throw read.error;const chosen=await client.functions.invoke('bright-processor',{body:{type:'choose',starter:b.dataset.species,revision:read.data.revision,operationId:crypto.randomUUID()}});if(chosen.error||chosen.data?.error)throw Error(chosen.data?.error||'Scelta non riuscita. Riprova.');await load();}catch(e){message=e.message;await load();}finally{busy=false;render();}return;}if(a==='reload')await load();if(a==='heal')await perform(()=>window.RouteEncounters.healTeam());if(a==='battle'){try{await window.RouteEncounters.resumeActive();await load();}catch(e){message=e.message;render();}}if(a==='release'||a==='replace')confirmRelease(b.dataset.uid,a==='replace');if(a==='up'||a==='down')await perform(()=>api.movePokemonInTeam(Number(b.dataset.index),Number(b.dataset.index)+(a==='up'?-1:1)));if(a==='accept')await perform(()=>api.acceptPending());if(a==='later'){pendingHidden=true;render();}if(a==='resume'){pendingHidden=false;render();}});
 root.addEventListener('error',e=>{if(e.target.tagName==='IMG'){e.target.removeAttribute('src');e.target.alt='Sprite non disponibile';}},true);
 await load();if(!current())return;
}
